### Creating DB ###

DROP DATABASE IF EXISTS `NEDB`;
CREATE DATABASE `NEDB` CHARSET=utf8 COLLATE=utf8_spanish_ci;

### Creating Tables ###

/*
PERSONA, FAMILIA, APARTAMENTO, BLOQUE, LIDER, BRIGADISTA, USUARIO

LUGAR, TRABAJO, ESCOLARIZACION

ENFERMEDAD, TIPOENFERMEDAD, MEDICAMENTO, RECETA, AYUDATECNICA, TIPOAYUDATECNICA, DISCAPACIDAD, TIPODISCAPACIDAD

CARNET, BONO, BONORECIBIDO, PROGRAMASOCIAL, PROGRAMAASIGNADO, BENEFICIO

BOMBONA, TIPOBOMBONA, MARCABOMBONA
*/

CREATE TABLE `PERSONA`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRES` VARCHAR(255),
	`APELLIDOS` VARCHAR(255),
	`GENERO` ENUM('M','F'),
	`DNI` INT UNIQUE,
	`TELEFONO` VARCHAR(255),
	`POSICION` ENUM('JEFE','PAREJA','HERMANO','HIJO','PADRE','TIO','SOBRINO','NIETO','ABUELO','BISABUELO','BISNIETO',
		'OTRO'),
	`EMBARAZO` ENUM('S','N'),
	`ENCAMADO` ENUM('S','N'),
	`PENSION` ENUM('NT', 'AM', 'SS'),
	`VOTO` ENUM('D','B','O'),
	`FECHA_NAC` DATE,
	`PESO` FLOAT,
	`ESTATURA` FLOAT,
	`ID_FAMILIA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `LUGAR`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(255),
	`TIPO` ENUM('PUBLICO','PRIVADO'),
	`TIPO_INSTITUCION` ENUM('POLITICA', 'ECONOMICA', 'JURIDICA', 'LABORAL', 'CIENTIFICA', 'DE SALUD',
		'EDUCATIVA', 'ARTISTICA', 'NINGUNO'),
	`RIF` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `TRABAJO`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ID_LUGAR` INT,
	`ID_PERSONA` INT,
	`DESCRIPCION` TEXT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `ESCOLARIZACION`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ID_INSTITUCION` INT,
	`NIVEL_EDUCACIONAL` ENUM('MATERNAL','PREESCOLAR','PRIMARIA','SECUNDARIA','UNIVERSIDAD'),
	`DESCRIPCION` TEXT,
	`ID_PERSONA` INT UNIQUE,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `ENFERMEDAD`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ID_TIPOENFERMEDAD` INT,
	`ID_PERSONA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `TIPOENFERMEDAD`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `DISCAPACIDAD`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`ID_TIPO` INT,
	`ID_PERSONA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `TIPODISCAPACIDAD`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`TIPO` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `MEDICAMENTO`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(255),
	`TIPO` ENUM('ORAL','RECTAL/VAGINAL', 'INTRAMUSCULAR', 'INTRAVENOSA', 'TOPICO', 'INTRADERMICA',
		'OPTICA', 'OFTALMICA/NASAL'),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `RECETA`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`DESCRIPCION` TEXT,
	`ID_PERSONA` INT,
	`ID_MEDICAMENTO` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `AYUDATECNICA`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ID_PERSONA` INT,
	`ID_TIPOAYUDATECNICA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `TIPOAYUDATECNICA`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `CARNET`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`SERIAL_CARNET` VARCHAR(255),
	`CODIGO_CARNET` VARCHAR(255),
	`ID_PERSONA` INT UNIQUE,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `BONO`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `BONORECIBIDO`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ID_BONO` INT,
	`ID_CARNET` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `PROGRAMASOCIAL`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `PROGRAMAASIGNADO`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ID_PROGRAMA` INT,
	`ID_PERSONA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `BOMBONA`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`ID_FAMILIA` INT,
	`ID_TIPO` INT(2),
	`ID_MARCA` INT(2),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `TIPOBOMBONA`(
	`ID`INT(2) NOT NULL AUTO_INCREMENT,
	`TIPO` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `MARCABOMBONA`(
	`ID`INT(2) NOT NULL AUTO_INCREMENT,
	`MARCA` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `FAMILIA`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`ID_APARTAMENTO` INT,
	`ESTADO_VIVIENDA` ENUM('PROPIO', 'ALQUILADO', 'ASEDIADO'),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `APARTAMENTO`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`NUMERO_APARTAMENTO` VARCHAR(5),
	`CODIGO` VARCHAR(255),
	`SERIAL` INT,
	`ANEXO` ENUM('S','N'),
	`ID_BLOQUE` INT(1),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `BLOQUE`(
	`ID`INT(1) NOT NULL AUTO_INCREMENT,
	`NUMERO_BLOQUE` INT(2) UNSIGNED ZEROFILL,
	`CODIGO` VARCHAR(255),
	`SERIAL` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `BENEFICIO`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`FECHA_ENTREGA` DATE,
	`CANTIDAD` INT,
	`ID_FAMILIA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `LIDER`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRES` VARCHAR(255),
	`APELLIDOS` VARCHAR(255),
	`DNI` INT,
	`TELEFONO` VARCHAR(255),
	`ID_BLOQUE` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `BRIGADISTA`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRES` VARCHAR(255),
	`APELLIDOS` VARCHAR(255),
	`DNI` INT,
	`TELEFONO` VARCHAR(255),
	`ID_BLOQUE` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `USUARIO`(
	`ID` INT(1) NOT NULL AUTO_INCREMENT,
	`USUARIO` VARCHAR(255) UNIQUE,
	`NOMBRE` VARCHAR(255),
	`APELLIDO` VARCHAR(255),
	`CLAVE` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

### Creating foreign keys ###

ALTER TABLE `PERSONA`
	ADD FOREIGN KEY (`ID_FAMILIA`) REFERENCES `FAMILIA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `TRABAJO`
	ADD FOREIGN KEY (`ID_LUGAR`) REFERENCES `LUGAR` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ESCOLARIZACION`
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_INSTITUCION`) REFERENCES `LUGAR` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ENFERMEDAD`
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_TIPOENFERMEDAD`) REFERENCES `TIPOENFERMEDAD` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `RECETA`
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_MEDICAMENTO`) REFERENCES `MEDICAMENTO` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `AYUDATECNICA`
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_TIPOAYUDATECNICA`) REFERENCES `TIPOAYUDATECNICA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `CARNET`
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BONORECIBIDO`
	ADD FOREIGN KEY (`ID_CARNET`) REFERENCES `CARNET` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_BONO`) REFERENCES `BONO` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `LIDER`
	ADD FOREIGN KEY (`ID_BLOQUE`) REFERENCES `BLOQUE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BRIGADISTA`
	ADD FOREIGN KEY (`ID_BLOQUE`) REFERENCES `BLOQUE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PROGRAMAASIGNADO`
	ADD FOREIGN KEY (`ID_PROGRAMA`) REFERENCES `PROGRAMASOCIAL` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `DISCAPACIDAD`
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_TIPO`) REFERENCES `TIPODISCAPACIDAD` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BOMBONA`
	ADD FOREIGN KEY (`ID_FAMILIA`) REFERENCES `FAMILIA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_TIPO`) REFERENCES `TIPOBOMBONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_MARCA`) REFERENCES `MARCABOMBONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `FAMILIA`
	ADD FOREIGN KEY (`ID_APARTAMENTO`) REFERENCES `APARTAMENTO` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `APARTAMENTO`
	ADD FOREIGN KEY (`ID_BLOQUE`) REFERENCES `BLOQUE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BENEFICIO`
	ADD FOREIGN KEY (`ID_FAMILIA`) REFERENCES `FAMILIA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

### Adding default values ###

INSERT INTO `USUARIO` (`USUARIO`,`NOMBRE`,`APELLIDO`,`CLAVE`) VALUES
	('admin','admin','admin','1234');

INSERT INTO `BLOQUE` (`NUMERO_BLOQUE`) VALUES
	(14),(15),(16),(17),(18),(19),(20),(23);

INSERT INTO `APARTAMENTO` (`NUMERO_APARTAMENTO`,`ID_BLOQUE`,`ANEXO`) VALUES
	("00-01",1,'N'),("00-02",1,'N'),("00-03",1,'N'),("00-04",1,'N'),("00-05",1,'N'),("00-06",1,'N'),("00-07",1,'N'),
	("01-01",1,'N'),("01-02",1,'N'),("01-03",1,'N'),("01-04",1,'N'),("01-05",1,'N'),("01-06",1,'N'),("01-07",1,'N'),
	("02-01",1,'N'),("02-02",1,'N'),("02-03",1,'N'),("02-04",1,'N'),("02-05",1,'N'),("02-06",1,'N'),("02-07",1,'N'),
	("03-01",1,'N'),("03-02",1,'N'),("03-03",1,'N'),("03-04",1,'N'),("03-05",1,'N'),("03-06",1,'N'),("03-07",1,'N'),

	("00-01",2,'N'),("00-02",2,'N'),("00-03",2,'N'),("00-04",2,'N'),("00-05",2,'N'),("00-06",2,'N'),("00-07",2,'N'),
	("01-01",2,'N'),("01-02",2,'N'),("01-03",2,'N'),("01-04",2,'N'),("01-05",2,'N'),("01-06",2,'N'),("01-07",2,'N'),
	("02-01",2,'N'),("02-02",2,'N'),("02-03",2,'N'),("02-04",2,'N'),("02-05",2,'N'),("02-06",2,'N'),("02-07",2,'N'),
	("03-01",2,'N'),("03-02",2,'N'),("03-03",2,'N'),("03-04",2,'N'),("03-05",2,'N'),("03-06",2,'N'),("03-07",2,'N'),

	("00-01",3,'N'),("00-02",3,'N'),("00-03",3,'N'),("00-04",3,'N'),("00-05",3,'N'),("00-06",3,'N'),("00-07",3,'N'),
	("01-01",3,'N'),("01-02",3,'N'),("01-03",3,'N'),("01-04",3,'N'),("01-05",3,'N'),("01-06",3,'N'),("01-07",3,'N'),
	("02-01",3,'N'),("02-02",3,'N'),("02-03",3,'N'),("02-04",3,'N'),("02-05",3,'N'),("02-06",3,'N'),("02-07",3,'N'),
	("03-01",3,'N'),("03-02",3,'N'),("03-03",3,'N'),("03-04",3,'N'),("03-05",3,'N'),("03-06",3,'N'),("03-07",3,'N'),

	("00-01",4,'N'),("00-02",4,'N'),("00-03",4,'N'),("00-04",4,'N'),("00-05",4,'N'),("00-06",4,'N'),("00-07",4,'N'),
	("01-01",4,'N'),("01-02",4,'N'),("01-03",4,'N'),("01-04",4,'N'),("01-05",4,'N'),("01-06",4,'N'),("01-07",4,'N'),
	("02-01",4,'N'),("02-02",4,'N'),("02-03",4,'N'),("02-04",4,'N'),("02-05",4,'N'),("02-06",4,'N'),("02-07",4,'N'),
	("03-01",4,'N'),("03-02",4,'N'),("03-03",4,'N'),("03-04",4,'N'),("03-05",4,'N'),("03-06",4,'N'),("03-07",4,'N'),

	("00-01",5,'N'),("00-02",5,'N'),("00-03",5,'N'),("00-04",5,'N'),("00-05",5,'N'),("00-06",5,'N'),("00-07",5,'N'),
	("01-01",5,'N'),("01-02",5,'N'),("01-03",5,'N'),("01-04",5,'N'),("01-05",5,'N'),("01-06",5,'N'),("01-07",5,'N'),
	("02-01",5,'N'),("02-02",5,'N'),("02-03",5,'N'),("02-04",5,'N'),("02-05",5,'N'),("02-06",5,'N'),("02-07",5,'N'),
	("03-01",5,'N'),("03-02",5,'N'),("03-03",5,'N'),("03-04",5,'N'),("03-05",5,'N'),("03-06",5,'N'),("03-07",5,'N'),

	("00-01",6,'N'),("00-02",6,'N'),("00-03",6,'N'),("00-04",6,'N'),("00-05",6,'N'),("00-06",6,'N'),("00-07",6,'N'),("00-08",6,'N'),("00-09",6,'N'),("00-10",6,'N'),
	("01-01",6,'N'),("01-02",6,'N'),("01-03",6,'N'),("01-04",6,'N'),("01-05",6,'N'),("01-06",6,'N'),("01-07",6,'N'),("01-08",6,'N'),("01-09",6,'N'),("01-10",6,'N'),
	("02-01",6,'N'),("02-02",6,'N'),("02-03",6,'N'),("02-04",6,'N'),("02-05",6,'N'),("02-06",6,'N'),("02-07",6,'N'),("02-08",6,'N'),("02-09",6,'N'),("02-10",6,'N'),
	("03-01",6,'N'),("03-02",6,'N'),("03-03",6,'N'),("03-04",6,'N'),("03-05",6,'N'),("03-06",6,'N'),("03-07",6,'N'),("03-08",6,'N'),("03-09",6,'N'),("03-10",6,'N'),

	("00-01",7,'N'),("00-02",7,'N'),("00-03",7,'N'),("00-04",7,'N'),("00-05",7,'N'),("00-06",7,'N'),("00-07",7,'N'),
	("01-01",7,'N'),("01-02",7,'N'),("01-03",7,'N'),("01-04",7,'N'),("01-05",7,'N'),("01-06",7,'N'),("01-07",7,'N'),
	("02-01",7,'N'),("02-02",7,'N'),("02-03",7,'N'),("02-04",7,'N'),("02-05",7,'N'),("02-06",7,'N'),("02-07",7,'N'),
	("03-01",7,'N'),("03-02",7,'N'),("03-03",7,'N'),("03-04",7,'N'),("03-05",7,'N'),("03-06",7,'N'),("03-07",7,'N'),

	
	("00-01",8,'N'),("00-02",8,'N'),("00-03",8,'N'),("00-04",8,'N'),("00-05",8,'N'),("00-06",8,'N'),("00-07",8,'N'),("00-08",8,'N'),
	("01-01",8,'N'),("01-02",8,'N'),("01-03",8,'N'),("01-04",8,'N'),("01-05",8,'N'),("01-06",8,'N'),("01-07",8,'N'),("01-08",8,'N'),
	("02-01",8,'N'),("02-02",8,'N'),("02-03",8,'N'),("02-04",8,'N'),("02-05",8,'N'),("02-06",8,'N'),("02-07",8,'N'),("02-08",8,'N'),
	("03-01",8,'N'),("03-02",8,'N'),("03-03",8,'N'),("03-04",8,'N'),("03-05",8,'N'),("03-06",8,'N'),("03-07",8,'N'),("03-08",8,'N');
